### ISSUE TITLE
How to display and store rewards

### ISSUE THREAD

**Issue by zakblacki** [some-one-who-codez/Flutter-mobile-ads#2]
I'd like to show display this  `print('You eanred ${reward.amount} ${reward.type}');` on the screen text() 
how to do that ? 
For example if user earn enough point he can convert them to upgrade subscription VIP

**Comment by agmada-asa** [comment]
You would need to pass the `reward.amount` and `reward.type` to your next screen through a parameter of type `RewardItem` and then compare whether their total rewards are enough to convert for the subscription.

Then you simply need to use something like `Text('You earned ${widget.reward.amount}');`
